import { point } from '@turf/helpers';
import distance from '@turf/distance';
import nearbyCities from 'nearby-cities';

export default function findNearbyCities(lat, lon) {
  const citiesConstants = [
    'Agartala',
    'Agra',
    'Ahmedabad',
    'Ahmednagar',
    'Ajmer',
    'Aligarh',
    'Allahabad',
    'Ambala',
    'Amritsar',
    'Anand',
    'Anantapur',
    'Andhra Pradesh - Other',
    'Arunachal Pradesh - Other',
    'Assam - Other',
    'Aurangabad',
    'Bareilly',
    'Bathinda',
    'Belgaum',
    'Bhopal',
    'Bidar',
    'Bihar - Other',
    'Calicut',
    'Chandigarh',
    'Chennai',
    'Coimbatore',
    'Cuttack',
    'Silvassa',
    'Daman & Diu',
    'Dehradun',
    'Delhi',
    'Dhanbad',
    'Dharwad',
    'Durgapur',
    'Erode',
    'Faridabad',
    'Gandhinagar',
    'Gangtok',
    'Ghaziabad',
    'Goa - Other',
    'Gorakhpur',
    'Gujarat - Other',
    'Gulbarga',
    'Guntur',
    'Gurgaon',
    'Guwahati',
    'Gwalior',
    'Haldia',
    'Haryana - Other',
    'Himachal Pradesh - Other',
    'Hisar',
    'Hubli',
    'Imphal',
    'Indore',
    'Itanagar',
    'Jabalpur',
    'Jaipur',
    'Jaisalmer',
    'Jalandhar',
    'Jalgaon',
    'Jammu',
    'Jammu & Kashmir - Other',
    'Jamnagar',
    'Jamshedpur',
    'Jharkhand - Other',
    'Jodhpur',
    'Kanpur',
    'Karnataka - Other',
    'Kerala - Other',
    'Kharagpur',
    'Kochi',
    'Kolhapur',
    'Kolkata',
    'Kollam',
    'Kota',
    'Kottayam',
    'Kurnool',
    'Kurukshetra',
    'Lucknow',
    'Ludhiana',
    'Madhya Pradesh - Other',
    'Madurai',
    'Maharashtra - Other',
    'Mangalore',
    'Manipur - Other',
    'Mathura',
    'Meerut',
    'Meghalaya - Other',
    'Mizoram - Other',
    'Moradabad',
    'Mumbai',
    'Mysore',
    'Nagaland - Other',
    'Nagercoil',
    'Nagpur',
    'Navi Mumbai',
    'Nellore',
    'Nizamabad',
    'Noida',
    'Ooty',
    'Orissa - Other',
    'Panipat',
    'Patna',
    'Pondicherry',
    'Pune',
    'Puri',
    'Raipur',
    'Rajasthan - Other',
    'Rajkot',
    'Ranchi',
    'Rohtak',
    'Roorkee',
    'Rourkela',
    'Salem',
    'Shillong',
    'Shimla',
    'Sikkim - Other',
    'Siliguri',
    'Solapur',
    'Srinagar',
    'Surat',
    'Tamil Nadu - Other',
    'Thanjavur',
    'Tirunelveli',
    'Tirupati',
    'Tripura - Other',
    'Udaipur',
    'Ujjain',
    'Uttar Pradesh - Other',
    'Varanasi',
    'Vasco Da Gama',
    'Vellore',
    'Vijayawada',
    'Visakhapatnam',
    'Warangal',
    'West Bengal - Other',
    'Manipal',
    'Bangalore',
    'Hoskote',
    'Khammam',
    'Hyderabad',
    'Chittoor',
    'Secunderabad',
    'Raichur',
    'Tumkur',
    'Dibrugarh',
    'Gaya',
    'Bhagalpur',
    'Muzaffarpur',
    'Bhilai',
    'Thiruvananthapuram',
    'Kaithal',
    'Solan',
    'Mandi',
    'Kullu',
    'Kozhikode',
    'Bijapur',
    'Davangere',
    'Shimoga',
    'Chitradurga',
    'Udupi',
    'Hassan',
    'Dhule',
    'Akola',
    'Amravati',
    'Sangli',
    'Satara',
    'Thane',
    'Raigad',
    'Wardha',
    'Parbhani',
    'Nanded',
    'Latur',
    'Nashik',
    'Ganjam',
    'Faridkot',
    'Patiala',
    'Kodaikanal',
    'Modinagar',
    'Saharanpur',
    'Jaunpur',
    'Rishikesh',
    'Howrah',
    'Bardhaman',
    'Murshidabad',
    'Bhubaneswar',
    'Murthal',
    'Tiruchirappalli',
    'Punjab - Other',
    'Karimnagar',
    'Karur',
    'Midnapore',
    'Nalanda',
    'Tezpur',
    'Wayanad',
    'District 24 Parganas',
    'Aizawl',
    'Alwar',
    'Bhilwara',
    'Bikaner',
    'Bundi',
    'Darjeeling',
    'Ferozpur',
    'Ghazipur',
    'Greater Noida',
    'Haridwar',
    'Kanchipuram',
    'Kanyakumari',
    'Kohima',
    'Ladakh',
    'Lakshadweep',
    'Leh',
    'Mapusa',
    'Margao',
    'Moga',
    'Muktsar',
    'Nainital',
    'Panaji',
    'Pathanamthitta',
    'Ponda',
    'Sonepat',
    'Vadodara',
    'Vaishali',
    'Yamuna Nagar',
    'Yavatmal',
    'All over India',
    'Kadapa',
    'Bokaro Steel City',
    'Dispur',
    'Rajgir',
    'Hampi',
    'Alleppey',
    'Kumarakom',
    'Kovalam',
    'Munnar',
    'Thekkady',
    'Canacona',
    'Old Goa',
    'Manali',
    'Dharamsala',
    'Gulmarg',
    'Pahalgam',
    'Orchha',
    'Khajuraho',
    'Konark',
    'Ranakpur',
    'Shekhawati',
    'Rameshwaram',
    'Andaman Nicobar Islands',
    'Delhi/NCR',
    'Mumbai (All)',
    'Uttarakhand - Other',
    'Chhattisgarh - Other',
    'Sirmour',
    'Nawanshahar',
    'Sriganaganagar',
    'Dadri',
    'Chikballpura',
    'Coorg',
    'Doballapura',
    'Kannur',
    'Idukki',
    'Kasargode',
    'Thrissur',
    'Dadra And Nagar Haveli - Other',
    'Harihar',
    'Trichy',
    '',
    'Adipur',
    'Bhavnagar',
    'Amritapuri',
    'BilasPur',
    'Kutch District',
    'Sagar',
    'Gandhidham',
    'Bharatpur',
    'Phagwara',
    'Karnal',
    'Jorhat',
    'Silchar',
    'Arrah',
    'Hajipur',
    'Una',
    'Rewari',
    'Kalyani',
    'Raigarh Pen',
    'Bharuch',
    'Nagaon',
    'Navsari',
    'Baghpat',
    'Bulandshahr',
    'Hapur',
    'Jhajjar',
    'Bahadurgarh',
    'Bhiwadi',
    'Neemrana',
    'Delhi - Other',
    'Pilani',
    'Muzaffarnagar',
    'Karaikudi',
    'Haldwani',
    'Bilaspur(CG)',
    'Townsville City',
    'Melbourne',
    'Sydney',
    'Perth',
    'Brisbane',
    'Lismore',
    'Canberra',
    'Adelaide',
    'Fremantle',
    'Ballarat',
    'Armidale',
    'Newcastle',
    'Toowoomba',
    'Hobart',
    'Launceston',
    'Sunshine Coast',
    'Wollongong',
    'Wolfville',
    'Sault Ste. Marie',
    'Sherbrooke',
    'London',
    'St. Catharines',
    'Winnipeg',
    'Cape Breton',
    'Ottawa',
    'Montreal',
    'Halifax',
    'Vancouver',
    'Regina',
    'Richmond',
    'Thunder Bay',
    'Orillia',
    'Greater Sudbury',
    'Edmonton',
    'Hamilton',
    "St. John's",
    'Sackville',
    'Calgary',
    'North Bay',
    'Toronto',
    'Kingston',
    'Colwood',
    'Burnaby',
    'Antigonish',
    'Fredericton',
    'Kamloops',
    'Peterborough',
    'Langley',
    'Guelph',
    'Lethbridge',
    'Prince George',
    'Oshawa',
    'Charlottetown',
    'Saskatoon',
    'Abbotsford',
    'Victoria',
    'Waterloo',
    'Windsor',
    'Nanaimo',
    'Cambridge',
    'Chelmsford',
    'Peterborough',
    'Birmingham',
    'Bangor',
    'Bath',
    'Bournemouth',
    'Cardiff',
    'Cranfield',
    'Leicester',
    'Ormskirk',
    'Edinburgh',
    'Glasgow',
    'Wrexham',
    'London',
    'Keele',
    'Kingston upon Thames',
    'Lancaster',
    'Liverpool',
    'Loughborough',
    'Newcastle upon Tyne',
    'Nottingham',
    'Egham',
    'Sheffield',
    'Southampton',
    'Swansea',
    'Middlesbrough',
    'Belfast',
    'Aberdeen',
    'Buckingham',
    'Northampton',
    'Winchester',
    'York',
    'Wolverhampton',
    'Coventry',
    'Londonderry',
    'Paisley',
    'Hamilton',
    'Bristol',
    'Inverness',
    'Brighton',
    'Guildford',
    'Sunderland',
    'St Andrews',
    'Salford',
    'Reading',
    'Portsmouth',
    'Oxford',
    'Manchester',
    'Leeds',
    'Kingston upon Hull',
    'Huddersfield',
    'Hatfield',
    'Exeter',
    'Colchester',
    'Norwich',
    'Durham',
    'Dundee',
    'Derby',
    'Carlisle',
    'Ambleside',
    'Barrow-in Furness',
    'Penrith',
    'Chichester',
    'Chester',
    'Bradford',
    'Bolton',
    'Luton',
    'Karlsruhe',
    'Cambridge',
    'Surrey',
    'Casuarina',
    'Kensington',
    'Daytona Beach',
    'Joondalup',
    'Jonesboro',
    'Auburn',
    'Waltham',
    'North Miami',
    'Ypsilanti',
    'Hackensack',
    'Albury',
    'Boston',
    'Burwood',
    'St. Charles',
    'Clemson',
    'Murray',
    'Santa Clara',
    'East Lansing',
    'Nelson',
    'Auckland',
    'Bloomington',
    'New York',
    'Chicago',
    'Lawrence',
    'Pasadena',
    'Grand Rapids',
    'Salt Lake',
    'Hamilton',
    'Ann Arbor',
    'New Orleans',
    'Honolulu',
    'Medford',
    'Milwaukee',
    'San Diego',
    'Cape Girardeau',
    'Tallahassee',
    'Hooksett',
    'Old Westbury',
    'Towson',
    'Provo',
    'Newark',
    'Springfield',
    'Denver',
    'Princeton',
    'Ada',
    'Gainesville',
    'Urbana',
    'Spokane',
    'Carlisle',
    'Marietta',
    'St. Cloud',
    'Columbia',
    'Saint John',
    'Houston',
    'Pittsburgh',
    'Baltimore',
    'Tuscaloosa',
    'Edmond',
    'Iowa City',
    'South Hadley',
    'Coral Gables',
    'Los Angeles',
    'Atlanta',
    'Tyler',
    'Singapore',
    'Hamburg',
    'Columbia',
    'Maryville',
    'West Hartford',
    'St. Louis',
    'Albion',
    'Wellington',
    'Adrian',
    'Riverside',
    'Palmerston',
    'San Jose',
    'Kensington',
    'Rome',
    'University Heights',
    'Lexington',
    'Durham',
    'Milan',
    'Redlands',
    'Venice',
    'Albany',
    'Evanston',
    'Worcester',
    'Troy',
    'Turin',
    'Florence',
    'Munich',
    'Madison',
    'State College',
    'Murfreesboro',
    'Frankfurt',
    'Potsdam',
    'West Haven',
    'Notre Dame',
    'Rochester',
    'Dubai',
    'Dublin',
    'Ljubljana',
    'Charlottesville',
    'Nanjing',
    'Budapest',
    'Mount Pleasant',
    'Rennes',
    'Paris',
    'Daejeon',
    'Athens',
    'Kaunas',
    'Fresno',
    'Jonkoping',
    'Linkoping',
    'Rouen',
    'Barcelona',
    'Belgorod',
    'Tallinn',
    'Cape Town',
    'Nijmegen',
    'Kuala Lumpur',
    'Luxembourg',
    'Moscow',
    'Peoria',
    'Shinjuku',
    'Madrid',
    'Birmingham',
    'Nilai',
    'Lugansk',
    'Gothenburg',
    'Maastricht',
    'San Francisco',
    'St. Gallen',
    'Donetsk',
    'Zaporozhye',
    'Bozeman',
    'Rotterdam',
    'Burlington',
    'Tartu',
    'Johor Bahru',
    'Cracow',
    'Brussels',
    'Big Rapids',
    'Austin',
    'Napier',
    'Gengenbach',
    'Wroclaw',
    'Bedong',
    'Suva',
    'Wageningen',
    'Heidelberg',
    'Kent',
    'Durham',
    'Ajman',
    'Providence',
    'Lewisburg',
    'Stirling',
    'Lausanne',
    'Hanover',
    'Southfield',
    'Lewiston',
    'Saint Paul',
    'Leavenworth',
    'Pamplona',
    'Seattle',
    'Bangkok',
    'Stanford',
    'Emporia',
    'Poznan',
    'Vasteras',
    'Stockholm',
    'Newport',
    'Hamilton',
    'Alicante',
    'Nanning',
    'Beijing',
    'Irving',
    'Dayton',
    'New Haven',
    'Lincoln',
    'Matosinhos',
    'Warsaw',
    'Bergen',
    'Nizhny Novgorod',
    'Orenburg',
    'Bronxville',
    'Robina',
    'Sydney',
    'Richmond',
    'Eugene',
    'Pomona',
    'Lawton',
    'Washington',
    'Grinnell',
    'Middlebury',
    'Aberdeen',
    'Rockhampton',
    'Callaghan',
    'Maroochydore',
    'Ultimo',
    'Penrith',
    'Mankato',
    'Columbus',
    'Cookeville',
    'Bandar Sunway',
    'Waterford',
    'Suzhou',
    'Bronx',
    'Athens',
    'Rotorua',
    'Tauranga',
    'Southport',
    'Middlesbrough',
    'Canterbury',
    'Bolton',
    'Ithaca',
    'Sylvania',
    'Tampa',
    'Middlesex',
    'Lake Charles',
    'Dortmund',
    'Invercargill',
    'Cairns',
    'Lille',
    'Carbondale',
    'Stavropol',
    'Vilnius',
    'Falun',
    'South Bend',
    'Cologne',
    'Shannon',
    'Wuhan',
    'Monaco',
    'Barnet',
    'Dunedin',
    'Bharatpur',
    'Yichang',
    'Plymouth',
    'Minneapolis',
    'Klaipeda',
    'Longview',
    'New Rochelle',
    'Bowling Green',
    'North Andover',
    'Shanghai',
    'Philadelphia',
    'Berkeley',
    'Tbilisi',
    'Marseille',
    'Santa Cruz',
    'Irvine',
    'Traverse',
    'Kirkland',
    'College Park',
    'Chapel Hill',
    'Fort Lauderdale',
    'Seoul',
    'Pok Fu Lam',
    'Puerto Princesa',
    'Mont-Saint-Aignan',
    'Las Pinas',
    'Yuma',
    'Malda',
    'Rudrapur',
    'Hamirpur',
    'Ramgarh',
    'North Lakhimpur',
    'Dewas',
    'Baramati',
    'Izmir',
    'Geneva',
    'Bilbao',
    'Canterbury',
    'Arlington',
    'Kemaman',
    'Duluth',
    'Uppsala',
    'Nicosia',
    'Amsterdam',
    'Enschede',
    'Cork',
    'Kitchener',
    'Barrie',
    'Cranbrook',
    'Sarnia',
    'Bangi',
    'Belleville',
    'Oakville',
    'Castlegar',
    'Dawson Creek',
    'Nezhinskaya',
    'Kelowna',
    'Penang',
    'Melville',
    'Göttingen',
    'Augsburg',
    'Nashville',
    'Brooklyn',
    'Bamberg',
    'Bridgeport',
    'Athens',
    'Berlin',
    'Orem',
    'Esslingen',
    'Richmond',
    'Bonn',
    'Bayreuth',
    'Stuttgart',
    'Bremen',
    'Angeles',
    'Walla Walla',
    'Mannheim',
    'Santa Barbara',
    'Mansfield',
    'Watertown',
    'Monroeville',
    'Malta',
    'Oceanside',
    'El Cajon',
    'Sumiton',
    'Enterprise',
    'Tanner',
    'Dothan',
    'Brewton',
    'Alexander City',
    'Gadsden',
    'Albuquerque',
    'Selma',
    'Odense',
    'Bay Minette',
    'Rainsville',
    'Washington',
    'Muscle Shoals',
    'Boaz',
    'Wadley',
    'Hanceville',
    'Blytheville',
    'Beebe',
    'Marion',
    'Cergy-Pontoise',
    'Phil Campbell',
    'Bellevue',
    'Dallas',
    'Hempstead',
    'Springfield',
    'Costa Mesa',
    'Rockville',
    'Aberystwyth',
    'Portland',
    'Auburn',
    'New Wilmington',
    'Pleasant Hill',
    'Stoke-on-Trent',
    'Malaga',
    'Paramus',
    'Shoreline',
    'Lynnwood',
    'Plano',
    'Joplin',
    'Lincoln',
    'Christchurch',
    'Decatur',
    'Vigan',
    'Quincy',
    'Orlando',
    'Henderson',
    'Berkhamsted',
    'Bunbury',
    'Santa Monica',
    'Falmouth',
    'Mildura',
    'East Greenwich',
    'Warrnambool',
    'Canterbury',
    'Darlinghurst',
    'Griffith',
    'Aurora',
    'Port Macquarie',
    'Broken Hill',
    'Whangarei',
    'Gold Coast',
    'Geelong',
    'Orana',
    'Abilene',
    'Wodonga',
    'Garland',
    'New Plymouth',
    'San Angelo',
    'Worcester',
    'Karratha',
    'Wheaton',
    'Sherman',
    'Waco',
    'Bendigo',
    'Phoenix',
    'Cape Town',
    'Lund',
    'City of San Antonio',
    'Lake Jackson',
    'Poole',
    'Tucson',
    'Brownwood',
    'Ames',
    'Cincinnati',
    'College Station',
    'Tempe',
    'Amherst',
    'Newark',
    'Boulder',
    'West Lafayette',
    'Richardson',
    'Cleveland',
    'Buffalo',
    'Wurzburg',
    'Baton Rouge',
    'Melbourne',
    'Morgantown',
    'Fayetteville',
    'Syracuse',
    'Washington D.C.',
    'Lubbock',
    'Knoxville',
    'Marshall',
    'Suffolk',
    'Cirencester',
    'Twickenham',
    'Preston',
    'Wycombe',
    'Suffolk',
    'Canterbury',
    'Edinburgh',
    'Flagstaff',
    'Starkville',
    'Fort Worth',
    'Milton Keynes',
    'Cheltenham',
    'Norman',
    'Williamsburg',
    'Binghamton',
    'Glendale',
    'Davis',
    'Beaumont',
    'Fort Collins',
    'Lincoln',
    'Corvallis',
    'Blacksburg',
    'Winston-Salem',
    'Fairfax',
    'Memphis',
    'Oxford',
    'Miami',
    'Thousand Oaks',
    'Tulsa',
    'Raleigh',
    'Euless',
    'Midland',
    'Midland',
    'Hawkins',
    'Huntsville',
    'Wichita Falls',
    'Savannah',
    'Kerrville',
    'Bethlehem',
    'Golden',
    'Rochester',
    'Regensburg',
    'Marburg',
    'Tarragona',
    'Kenne',
    'Nacogdoches',
    'Georgetown',
    'El Paso',
    'Stephenville',
    'Alpine',
    'Herndon',
    'McAllen',
    'Seguin',
    'San Marcos',
    'Denton',
    'San Antonio',
    'Brownsville',
    'Pasadena',
    'Aachen',
    'Belton',
    'Darmstadt',
    'Plainview',
    'Canyon',
    'Laguna Hills',
    'Yellow Springs',
    'Oakland',
    'Arden Hills',
    'Rohnert Park',
    'Inverness',
    'San Luis Obispo',
    'Vallejo',
    'City of Orange',
    'Sonora',
    'San Rafael',
    'Claremont',
    'Stockton',
    'Perth',
    'Arcata',
    'Brunswick',
    'Fremont',
    'Belmont',
    'Laguna Beach',
    'Moraga',
    'Hayward',
    'Atherton',
    'Monterey',
    'Loma Linda',
    'Aliso Viejo',
    'Bakersfield',
    'Napa Valley',
    'San Dimas',
    'City of Redding',
    'Cypress',
    'Merced',
    'Deerfield',
    'Dresden',
    'Utrecht',
    'Rocklin',
    'Elmira',
    'Patchogue',
    'Rosemead',
    'Salem',
    'Seri Kembangan',
    'Oyster Bay',
    'Clinton',
    'Oneonta',
    'Hamburg',
    'Geneva',
    'St. Lawrence',
    'Jamestown',
    'City of Poughkeepsie',
    'Caneadea',
    'Allegany',
    'Harrison',
    'Long Island City',
    'St. Augustine',
    'Erlangen',
    'Oakdale',
    'Orangetown',
    'Greenburgh',
    'Akron',
    'Town of Brookhaven',
    'Downers Grove',
    'Toledo',
    'Amherst',
    'Sweden',
    'Syosset',
    'Cortland',
    'Alfred',
    'Saratoga Springs',
    'Geneseo',
    'Cheney',
    'Madison County',
    'Schenectady',
    'Kenmore',
    'Glen Cove',
    'Newburgh',
    'Ellensburg',
    'New Paltz',
    'Leiden',
    'Hays',
    'Lacey',
    'Delhi',
    'Tacoma',
    'Toppenish',
    'Brighton',
    'Oswego',
    'Pullman',
    'Utica',
    'Centralia',
    'Redmond',
    'Pasco',
    'Bellingham',
    'Plymouth',
    'Plattsburgh',
    'Aurora',
    'Ottawa',
    'Cobleskill',
    'La Crosse',
    'Lisle',
    'Bloomington',
    'Normal',
    'Ripon',
    'Carlinville',
    'Fond du Lac',
    'Rock Island',
    'Olympia',
    'Romeoville',
    'De Pere',
    'Keshena',
    'Kenosha',
    'Waukesha',
    'Beloit',
    'Green Bay',
    'University Park',
    'River Forest',
    'Elgin',
    'Charleston',
    'Eureka',
    'Greenville',
    'Galesburg',
    'Bloomington',
    'Lake Forest',
    'Decatur',
    'Monmouth',
    'Jacksonville',
    'Lincoln',
    'Quincy',
    'Rockford',
    'Anderson',
    'Macomb',
    'Joliet',
    'Canton of Valais',
    'DeKalb',
    'Muncie',
    'Lebanon',
    'Terre Haute',
    'Subang Jaya',
    'Mishawaka',
    'Marion',
    'Fort Wayne',
    'Carmel',
    'Indianapolis',
    'Oakland City',
    'White Plains',
    'The Hague',
    'Evansville',
    'Huntington',
    'Whiting',
    'Angola',
    'Palos Heights',
    'Greencastle',
    'North Manchester',
    'Franklin',
    'Long Island',
    'Upland',
    'Valparaiso',
    'Bexley',
    'Little Falls',
    'Vincennes',
    'Crawfordsville',
    'Salem',
    'Mount Vernon',
    'Goshen',
    'Cedarville',
    'Tiffin',
    'Rensselaer',
    'Wilberforce',
    'Hanover',
    'Sugar Creek Township',
    'Delaware',
    'Hiram',
    'Westerville',
    'Belfast',
    'Bowling Green',
    'Bluffton',
    'Berea',
    'Ashland',
    'Gambier',
    'South Euclid',
    'Kettering',
    'Findlay',
    'Urbana',
    'Painesville',
    'Oberlin',
    'Ernakulum',
    'Langhorne',
    'Wooster',
    'Canton',
    'California',
    'Reading',
    'Rootstown',
    'Portsmouth',
    'Rio Grande',
    'Lima',
    'Radnor',
    'Alliance',
    'Erie',
    'Bloomsburg',
    'Lock Haven',
    'Allentown',
    'Defiance',
    'Lower Gwynedd Township',
    'Indiana',
    'Aston Township',
    'Wilmington',
    'Scranton',
    'Granville',
    'East Pennsboro',
    'Meadville',
    'Immaculata',
    'Steubenville',
    'Bryn Athyn',
    'Tubingen',
    'Munster',
    'Mainz',
    'Freiburg im Breisgau',
    'New Baltimore',
    'Elizabethtown',
    'Konstanz',
    'Cresson',
    'Lancaster',
    'Annville Township',
    'Glenside',
    'Selinsgrove',
    'Shippensburg',
    'Greensburg',
    'Latrobe',
    'Williamsport',
    'Kiel',
    'Youngstown',
    'Lower Merion Township',
    'Dallas',
    'Coopersburg',
    'Manhattan',
    'Radnor Township',
    'Springfield',
    'Millersville',
    'Ulm',
    'Augusta–Richmond County',
    'Québec City',
    'Chester',
    'Beaver Falls',
    'Clarion',
    'Louisville',
    'Greenville',
    'Wilkes-Barre',
    'Mansfield',
    'North Canton',
    'East Stroudsburg',
    'Berrien Springs',
    'Stillwater',
    'Gettysburg',
    'West Chester',
    'Marquette',
    'Frankenlust Township',
    'Collegeville',
    'Spring Arbor Township',
    'White Rose City',
    'Allendale',
    'Holland',
    'Flint',
    'Troy',
    'Waynesburg',
    'Detroit',
    'Sault Ste. Marie',
    'Belfast',
    'Kochville Township',
    'Hancock',
    'Alma',
    'Phoenixville',
    'Kalamazoo',
    'Naples',
    'Washington',
    'Howell',
    'Bloomfield Hills',
    'Grove City',
    'Burlington',
    'Boca Raton',
    'Chambersburg',
    'Allen Park',
    'Haverford',
    'Harrisonburg',
    'Harrisburg',
    'Hialeah',
    'Ocala',
    'Jacksonville',
    'Fort Myers',
    'Houghton',
    'Swarthmore',
    'South Orange',
    'St. Petersburg',
    'Marianna',
    'Winter Park',
    'Fort Pierce',
    'Panama City',
    'Lakeland',
    'Lake City',
    'Temple Terrace',
    'Clearwater',
    'Olivet',
    'Ébène City',
    'Morris',
    'St. Leo',
    'Deland',
    'Bridgewater',
    'Pensacola',
    'West Palm Beach',
    'Framingham',
    'Springfield',
    'Rochester Hills',
    'Fitchburg',
    'Leesburg',
    'Avon Park',
    'Paxton',
    'Babson Park',
    'Ebene',
    'Kutztown',
    'Longmeadow',
    'Milton',
    'Shreveport',
    'Montgomery',
    'Jacksonville',
    'Beverly',
    'Livingstone',
    'Russellville',
    'Huntsville',
    'Homewood',
    'Mobile',
    'Lakewood',
    'Milledgeville',
    'Troy',
    'Tuskegee',
    'Fairbanks',
    'Anchorage',
    'New Britain',
    'Grand Junction',
    'Montevallo',
    'Arkadelphia',
    'Danbury',
    'Albany',
    'Florence',
    'Magnolia',
    'Dover',
    'Searcy',
    'Alamosa',
    'Americus',
    'Magnolia',
    'Gainesville',
    'Morrow',
    'Fairfield',
    'Conway',
    'Columbus',
    'Macon',
    'New Castle',
    'Windham',
    'Doral',
    'Greeley',
    'Dahlonega',
    'Groningen',
    'Siloam Springs',
    'Boise',
    'Fort Valley',
    'Waleska',
    'Statesboro',
    'Queen Elizabeth Olympic Park',
    'Wichita',
    'Courtenay',
    'Timmins',
    'Nampa',
    'Rome',
    'Pocatello',
    'Salina',
    'Topeka',
    'Delft',
    'Maui Island',
    'Olathe',
    'Cedar Rapids',
    'Marietta',
    'Dubuque',
    'Pittsburg',
    'Tilburg',
    'Fairfield',
    'Baldwin City',
    'Umeå',
    'Frankfort',
    'Ruston',
    'Clinton',
    'Thomasville',
    'Cedar Falls',
    'Des Moines',
    'Nantes',
    'Frostburg',
    'Bowie',
    'Davenport',
    'Davao City',
    'Valdosta',
    'Oskaloosa',
    'Richmond',
    'Williamsburg',
    'Sioux City',
    'Virginia Beach',
    'Lafayette',
    'Storm Lake',
    'Orono',
    'Bangor',
    'Bemidji',
    'Takoma Park',
    'Trivandrum',
    'Winona',
    'Marshall',
    'Grenoble',
    'Salisbury',
    'Eindhoven',
    'Portales',
    'Silver City',
    'Greenville',
    'Las Vegas',
    'Neills Creek',
    'Elizabeth City',
    'Boiling Spring',
    'High Point',
    'Las Cruces',
    'Cullowhee',
    'Jackson',
    'Bethany',
    'Ada',
    'Tahlequah',
    'Hattiesburg',
    'Oxford',
    'Itta Bena',
    'Ashland',
    'La Grande',
    'Oklahoma City',
    'Weatherford',
    'Monmouth',
    'Greensboro',
    'Smithfield',
    'Aarhus',
    'Bordeaux',
    'St. Julian',
    'Msida',
    'Pembroke',
    'Sikar',
    'Ankara',
    'Rajahmundry',
    'Medak',
    'Nalgonda',
    'Telangana-Other',
    'Kakinada',
    'Vizianagaram',
    'Chambery',
    'Santa Fe',
    'Shirpur',
    'Tver',
    'Moscow',
    'San Bernardino',
    'Galloway',
    'Brunswick',
    'Kowloon',
    'Istanbul',
    'Leipzig',
    'Rostock',
    'Chico',
    'Conway',
    'Fargo',
    'Sacramento',
    'Fullerton',
    'Port Elizabeth',
    'Turlock',
    'Abu Dhabi',
    'Cumberland County',
    'Madison',
    'Kharkiv',
    'Brookings',
    'Barbar',
    'Sioux Falls',
    'Ardmore',
    'Lebanon',
    'Johnson City',
    'Wenzhou',
    'Conway',
    'Kutaisi',
    'Debrecen',
    'Forest Grove',
    'South Kingstown',
    'Bristol',
    'Charlotte',
    'Rock Hill',
    'Willemstad',
    'Webster Groves',
    'Northfield',
    'Newton',
    'Maryville',
    'Union',
    'Roubaix',
    'Mahwah',
    'Ufa',
    'George Town',
    'Lucerne',
    'Carlow',
    '',
    'Namakkal',
    'Ranga Reddy',
    'Prakasam',
    'West Godavari',
    'East Godavari',
    'Virudhunagar',
    'Jhunjhunu',
    'Krishna',
    'Palakkad',
    'Ratnagiri',
    'Canton',
    'City of Colorado Springs',
    'Kota Bharu',
    'Kuantan',
    'Reutlingen',
    'Thessaloniki',
    'Cedar City',
    'Nangal',
    'Chandrapur',
    'Angul',
    'Jajpur',
    'Hazaribagh',
    'Singrauli',
    'Vapi',
    'Korba',
    'Ulhasnagar',
    'Chirimiri',
    'Neyveli',
    'Brahmapur',
    'Jhansi',
    'Serampore',
    'Asansol',
    'Naihati',
    'Sambalpur',
    'Hoboken',
    'Raigarh',
    'Lyon',
    'City of Falls Church',
    'Gateshead',
    'Warrensburg',
    'Rolla',
    'Stephenville',
    'Galway',
    'Maynooth',
    'Wayne',
    'Omaha',
    'Ingolstadt',
    'Dearborn',
    'Salem',
    'Springfield',
    'Georgetown',
    'Panchkula',
    'Mohali',
    'Hosur',
    'Lisbon',
    'Hoshiarpur',
    'Ropar',
    'Ocean County',
    'Chandigarh Tricity',
    'Monroe',
    'Kansas City',
    'Portland',
    'Carrollton',
    'City of Iloilo',
    'Brunswick',
    'Waterville',
    'Pella',
    'Mount Vernon',
    'Bar Harbor',
    'Jersey City',
    'St. George',
    'Rutland',
    'Chiyoda',
    "'s-Hertogenbosch",
    'Plymouth',
    'Šiauliai',
    'Glasgow',
    'Vlissingen',
    'Lenexa',
    'Lamoni',
    'Laurinburg',
    'Orange City',
    'Sanford',
    'Friedrichshafen',
    'Livonia',
    'Thibodaux',
    'Witten',
    'Plainfield',
    'Swansea',
    'Edwardsville',
    '.',
    'Kirksville',
    'Killeen',
    'Niceville',
    'Ewing Township',
    'New London',
    'Aberdeen',
    'Wise',
    'Limerick',
    'Cz?stochowa',
    'Czestochowa',
    'Lodz',
    'Kalmar',
    'Toulouse',
    'Fayetteville',
    'Padua',
    'Crookston',
    'Edinboro',
    'Alpharetta',
    'Vermillion',
    'Randolph',
    'Bluefield',
    'Sweet Briar',
    'Winchester',
    'Moorhead',
    'St. Joseph',
    'Clermont-Ferrand',
    'Siena',
    'Le Havre',
    'Newport',
    'Lynchburg',
    'Vallendar',
    'Natchitoches',
    'Lublin',
    'Bologna',
    'Naples',
    'Laramie',
    'Dartmouth',
    'Athlone',
    'Chadron',
    'Moka',
    'Nova Gorica',
    'Kavrepalanchok',
    'Angers',
    'Ogden',
    'Nancy',
    'Paderborn',
    'Cebu',
    'Pueblo',
    'Petersburg',
    'Breukelen',
    'Dharmapuri',
    'Hasselt',
    'Salem',
    'Manila',
    'Campbellsville',
    'Kennesaw',
    'Kristianstad',
    'Lappeenranta',
    'Dagupan',
    'Kingsville',
    'Trondheim',
    'Zurich',
    'Arlington',
    'Copenhagen',
    'Fayette',
    'Kokomo',
    'Wiesbaden',
    'Rheingau-Taunus-Kreis',
    'Kufstein',
    'Leeuwarden',
    'Nanchang',
    'Grand Forks',
    'Chemnitz',
    'Marina',
    'Carson',
    'San Marcos',
    'Yorkton',
    'Rapid City',
    'Welland',
    'El Monte',
    'Lincoln',
    'Beijing',
    'Letterkenny',
    'Poughkeepsie',
    'Katowice',
    'Montpellier',
    'Ormond Beach',
    'Cyberjaya',
    'Malibu',
    'New Westminster',
    'Rutherford',
    'Champaign',
    'Vienna',
    'Boone',
    'Bhimavaram',
    'Eluru',
    'Gudivada',
    'Guntakal',
    'Hindupur',
    'Machilipatnam',
    'Narasaraopet',
    'Ongole',
    'Srikakulam',
    'Tadepalligudem',
    'Tenali',
    'Kokrajhar',
    'Bagaha',
    'Begusarai',
    'Bettiah',
    'Buxar',
    'Chapra',
    'Darbhanga',
    'Dehri',
    'Jamalpur',
    'Jehanabad',
    'Katihar',
    'Kishanganj',
    'Madhubani',
    'Motihari',
    'Munger',
    'Nawada',
    'Purnia',
    'Saharsa',
    'Sasaram',
    'Sitamarhi',
    'Siwan',
    'North Goa',
    'Panjim',
    'South Goa',
    'Amreli',
    'Anjar',
    'Banaskantha',
    'Baroda',
    'Bhuj',
    'Botad',
    'Dahod',
    'Dang',
    'Deesa',
    'Kadi',
    'Kandla',
    'Khambhat',
    'Kheda',
    'Dwarka',
    'Gir',
    'Godhra',
    'Junagadh',
    'Mehsana',
    'Morbi',
    'Nadiad',
    'Palanpur',
    'Palitana',
    'Panchmahal',
    'Patan',
    'Porbandar',
    'Radhanpur',
    'Rajpipla',
    'Sabarkantha',
    'Surendranagar',
    'Valsad',
    'Viramgam',
    'Visnagar',
    'Ankleshwar',
    'Vallabh Vidyanagar',
    'Bhiwani',
    'Hansi',
    'Jind',
    'Loharu',
    'Mahendragarh',
    'Mewat',
    'Narnaul',
    'Palwal',
    'Sirsa',
    'Tohana',
    'Amb',
    'Baddi',
    'Bilaspur',
    'Chamba',
    'Dalhousie',
    'Kangra',
    'Kasauli',
    'Kinnaur',
    'Lahaul',
    'Nadaun',
    'Nurpur',
    'Palampur',
    'Parwanoo',
    'Rohru',
    'Sundernagar',
    'Anantnag',
    'Bandipora',
    'Baramulla',
    'Budgam',
    'Doda',
    'Ganderbal',
    'Kargil',
    'Kathua',
    'Kishtwar',
    'Kulgam',
    'Kupwara',
    'Poonch',
    'Pulwama',
    'Rajouri',
    'Ramban',
    'Reasi',
    'Samba',
    'Shopian',
    'Udhampur',
    'Bagalkot',
    'Ballari',
    'Bhadravati',
    'Chamarajanagar',
    'Chikkamagaluru',
    'Gadag',
    'Haveri',
    'Hospet',
    'Karwar',
    'Kolar',
    'Koppal',
    'Mandya',
    'Ramanagara',
    'Ranebennuru',
    'Yadgir',
    'Malappuram',
    'Ashoknagar',
    'Balaghat',
    'Betul',
    'Burhanpur',
    'Chhatarpur',
    'Chhindwara',
    'Damoh',
    'Dhar',
    'Gadarwara',
    'Guna',
    'Harda',
    'Hoshangabad',
    'Katni',
    'Khandwa',
    'Mandsaur',
    'Morena',
    'Panagar',
    'Panna',
    'Raisen',
    'Ratlam',
    'Rewa',
    'Satna',
    'Shahdol',
    'Umaria',
    'Vidisha',
    'Dimapur',
    'Paralakhemundi',
    'Balasore',
    'Baripada',
    'Berhampur',
    'Bhawanipatna',
    'Burla',
    'Chandipur',
    'Dhauli',
    'Dhenkanal',
    'Gopalpur',
    'Jeypore',
    'kalahandi',
    'Keonjhar',
    'Khurda',
    'Koraput',
    'Mayurbhanj',
    'Nagaon',
    'Pipli',
    'Raghurajpur',
    'Rayagada',
    'Satyabadi',
    'Taptapani',
    'Tinsukia',
    'Barnala',
    'Batala',
    'Beas',
    'Dasuya',
    'Derabassi',
    'Fatehgarh',
    'Fazilka',
    'Gobindgarh',
    'Gurdaspur',
    'Kapurthala',
    'Kharar',
    'Kurali',
    'Malerkotla',
    'Mansa',
    'Mukerian',
    'Nabha',
    'Pathankot',
    'Rajpura',
    'Rupnagar',
    'Sahibzada Ajit Singh Nagar',
    'Sangrur',
    'Shahid Bhagat Singh Nagar',
    'Sirhind',
    'Tarn Taran',
    'Zirakpur',
    'Balotra',
    'Banswara',
    'Barmer',
    'Beawar',
    'Chaksu',
    'Chittorgarh',
    'Churu',
    'Dausa',
    'Dholpur',
    'Dungarpur',
    'Gangapur',
    'Hanumangarh',
    'Jalore',
    'Jhalawar',
    'Karauli',
    'Kishangarh',
    'Kuchhaman',
    'Ladnun',
    'Laxmangarh',
    'Mount Abu',
    'Nagaur',
    'Pali',
    'Phulera',
    'PratapGarh',
    'Rajsamand',
    'Samdari',
    'Sawaimadhopur',
    'Sirohi',
    'Tonk',
    'Vanasthali/Banasthali',
    'Aruppukkottai',
    'Courtallam',
    'Cuddalore',
    'Dindigul',
    'Karuppayurani',
    'Krishnagiri',
    'Mettupalayam',
    'Nagapattinam',
    'Nanganallur',
    'Nellikuppam',
    'Palani',
    'Pollachi',
    'Thiruvarur',
    'Sriperumbudur',
    'Theni',
    'Thoothukudi',
    'Tirupur',
    'Tiruvannamalai',
    'Villupuram',
    'Amroha',
    'Azamgarh',
    'Bahraich',
    'Barabanki',
    'Dhampur',
    'Faizabad',
    'Firozabad',
    'Gonda',
    'Hardoi',
    'Hathras',
    'Kannauj',
    'Mirzapur',
    'Orai',
    'Pilibhit',
    'Prabudh Nagar',
    'Raebareli',
    'Rampur',
    'Robertsganj',
    'Shahjahanpur',
    'Shamli',
    'Sitapur',
    'Unnao',
    'Vrindavan',
    'Mussoorie',
    'Kashipur',
    'Alipurduar',
    'Baharampur',
    'Bankura',
    'Birbhum',
    'Chandannagar',
    'Contai',
    'Coochbehar',
    'Dakshin Dinajpur',
    'Digha',
    'Habra',
    'Hooghly',
    'Jalpaiguri',
    'Nadia',
    'Purulia',
    'Shantiniketan',
    'Shantipur',
    'Suri',
    'Uttar Dinajpur',
    'Amaravati',
    'Bangor',
    'Vaud',
    'Wilmington',
    'Medicine Hat',
    'Hannover',
    'Northfield',
    'Norfolk',
    'Pori',
    'Helsinki',
    'Hämeenlinna',
    'Kajaani',
    'Glassboro',
    'Highland Heights',
    'Commerce',
    'Spartanburg',
    'Las Vegas',
    'London',
    'Lowell',
    'Menomonie',
    'Bad Honnef',
    'Shepherdstown',
    'Spearfish',
    'Reno',
    'Craftsbury Common',
    'Frederick',
    'Bhusawal',
    'Tehsil Bhawanigarh',
    'Ranikhet',
    'Kanera',
    'Port Blair',
    'Dumka',
    'Matar',
    'Balod',
    'Allagadda',
    'Khadiya',
    'Kalol',
    'Mandideep',
    'Kahanpur',
    'Gopeshwar (Chamoli)',
    'Durg',
    'Shujalpur',
    'Pithoragarh',
    'Madison',
    'Huntington',
    'Geraldton',
    'Clinton',
    'Corpus Christi',
    'Montreux',
    'Chernivtsi',
    'Ternopil',
    'Ivano-Frankivsk',
    'Kiev',
    'Vinnytsia',
    'Uzhhorod',
    'Ryazan',
    'Nizhny Novgorod',
    'Gunupur',
    'Colorno',
    'Gokarneshwor',
    'Vermilion',
    'Lloydminster',
    'Brandon',
    'Riga',
    'Tralee',
    'Sligo',
    'Williamstown',
    'Pasighat',
    'Sibsagar',
    'Golaghat.',
    'Dhemaji',
    'Sipajhar',
    'Sorbhog',
    'Diphu',
    'Jagiroad',
    'Karimganj',
    'Morigaon',
    'Howli',
    'Basugaon',
    'Bengtol',
    'Bongaigaon',
    'Golakganj',
    'Changsari',
    'Bokajan',
    'Forbesganj',
    'Banka',
    'Madhepura',
    'Jamui',
    'Supaul',
    'Mohania',
    'Samastipur',
    'Kaimur Bhabua',
    'Bara Chakia',
    'Rajnandgaon',
    'Jagdalpur',
    'Kawardha',
    'Kabirdham',
    'Mahasamund',
    'Surajpur',
    'Dantewada',
    'Baikunthpur',
    'Ramanujganj',
    'Kondagaon',
    'Balodabazar',
    'Bhatapara',
    'Sukma',
    'Jashpur Nagar',
    'Kanker',
    'Narayanpur',
    'Ambikapur',
    'Bemetara',
    'Dhamtari',
    'Baradwar',
    'Pilar',
    'Verna',
    'Madgao',
    'Bambolim',
    'Dharbandora',
    'Vyara',
    'Dharma',
    'Modasa',
    'Balasinor',
    'Nuh',
    'Hassanpur',
    'Nissing',
    'Ferozpur Jhirka',
    'Mustafabad',
    'Hodal',
    'Ratia',
    'Ner Chowk',
    'Jhumritelaiya',
    'Madhupur',
    'Rehla',
    'Sahibganj',
    'Daltonganj',
    'Chaibasa',
    'Bishrampur',
    'Giridih',
    'Ghatsila',
    'Garhwa',
    'Godda',
    'Mihijam',
    'Sullia',
    'Kunthoor',
    'Bantwal',
    'Ponnampet',
    'Ujire',
    'Sirsi',
    'Moodbidri',
    'Honnavar',
    'Kollegal',
    'Bhatkal',
    'Nazarbad',
    'Belthangady',
    'Ankola',
    'Virajpet',
    'Punjalakatte',
    'Kumta',
    'Haliyal',
    'Subrahmanya',
    'Siddapur',
    'Honavar',
    'Pathanapuram',
    'Sheopur',
    'Jhabua',
    'Datia',
    'Sendhwa',
    'Barwani',
    'Sehore',
    'Lahar',
    'Shajapur',
    'Neemuch',
    'Jawad',
    'Shivpuri',
    'Ashta',
    'Sidhi',
    'Pachore',
    'Anuppur',
    'Nasrullaganj',
    'Mandleshwar',
    'Khargone',
    'Sanawad',
    'Gormi',
    'Biaora',
    'Gondia',
    'Beed',
    'Kankavli',
    'Kudal',
    'Chikhli',
    'Buldana',
    'Washim',
    'Malkapur',
    'Parli Vaijnath',
    'Jalna',
    'Osmanabad',
    'Palghar',
    'Shegaon',
    'Sindhudurg',
    'Dondaicha',
    'Bhandara',
    'Ambajogai',
    'Surtoli',
    'Gadchiroli',
    'Vaibhavwadi',
    'Shahada',
    'Dahanu',
    'Hingoli',
    'Sawantwadi',
    'Sultanpur',
    'Hatta',
    'Wada',
    'Akkalkuwa',
    'Kosara',
    'Khamgaon',
    'Ashti',
    'Boisar',
    'Bhokardan',
    'Badnapur',
    'Patoda',
    'Partur',
    'Kankavali',
    'Shirur (Kasar)',
    'Amgaon',
    'Achara',
    'Vengurla',
    'Sakoli',
    'Majalgaon',
    'Tondavali',
    'Kurtadi',
    'Maram',
    'Ri Bhoi',
    'Rajgangpur',
    'Deogarh',
    'Bargarh',
    'Jharsuguda',
    'Sundargarh',
    'Nayagarh',
    'Jagatsinghpur',
    'Khordha',
    'Bhadrak',
    'Paikmal',
    'Barpali',
    'Baran',
    'Rangpo',
    'Kilakarai',
    'Pudukkottai',
    'Madhuranthagam',
    'Sivaganga',
    'Thirumansoali',
    'Thirumayam',
    'Punalkulam',
    'Keeranur',
    'Vaniyambadi',
    'Perambalur',
    'Ariyalur',
    'Sivagangai',
    'Udayarpalayam',
    'Thiruvallur',
    'Jayankondam',
    'Arcot',
    'Paramakudi',
    'Thiruppatur',
    'Ramanathapuram',
    'The Nilgiris',
    'Udhagamandalam',
    'Kotagiri',
    'Pandalur',
    'Kadaladi Taluk',
    'Tiiruppathur',
    'Kavaraipettai',
    'Poovanthi',
    'Mahabubnagar',
    'Kodad',
    'Mulkalla',
    'Manthani',
    'Sultanpur',
    'Ibrahimpatnam',
    'Bhuvanagiri',
    'Ghatkesar',
    'Suryapet',
    'Mahbubnagar',
    'Kondapak',
    'Mallapur',
    'Kothagudem',
    'Sangareddy',
    'Peddapalli',
    'Adilabad',
    'Godavarikhani',
    'Medchal',
    'Siddipet',
    'Mancherial',
    'Jangaon',
    'Sandareddy',
    'Gadwal',
    'Dharnmanagar',
    'Ambassa',
    'Khumulwng',
    'Najibabad',
    'Bhadohi',
    'Amethi',
    'Fatehpur',
    'Kaushambi',
    'Banda',
    'Sambhal',
    'Kiratpur',
    'Etawah',
    'Kasganj',
    'Bijnor',
    'Farrukhabad',
    'Balrampur',
    'Ambedkar Nagar',
    'Sultanpur',
    'Budaun',
    'Mau',
    'Barnahal',
    'Lalitpur',
    'Mainpuri',
    'Ganjdundwara',
    'Seohara',
    'Maharajganj',
    'Najibabd',
    'Lakhimpur',
    'Prayagraj',
    'Pantnagar',
    'Srinagar Pauri Garhwal',
    'Tanakpur',
    'Ranichauri',
    'Rudraprayag',
    'Kotdwar',
    'Kichha',
    'Kalimpong',
    'Jhargram',
    'Pedong',
    'Changchun',
    'Parma',
    'Hangzhou',
    "Xi'an",
    'Chengdu',
    'Shantou',
    'Qingdao',
    'Shijiazhuang',
    'Kunming',
    'Shenyang',
    'Jinan',
    'Xiamen',
    'Zhengzhou',
    'Dhanmondi',
    'Turag',
    'Manikganj',
    'Comilla',
    'Uttara',
    'Nantong',
    'Biot',
    'Hong Kong',
    'Macau',
    'Chongqing',
    'Beijing',
    'Shanghai',
    'Tianjin',
    'York',
    'Irkutsk',
    'Astrakhan',
    'Ivanovo',
    'Courbevoie',
    'Red Deer',
    'Kemerovo',
    'Kursk',
    'Oryol',
    'Tomsk',
    'Smolensk',
    'Rostov-on-Don',
    'Tambov',
    'Amiens',
    'Terrace',
    'Saguenay',
    'La Rochelle',
    'Tula',
    'Tyumen',
    'Ulyanovsk',
    'Yekaterinburg',
    'Volgograd',
    'Voronezh',
    'Yaroslavl',
    'Lviv',
    'Dnipro',
    'Mykolaiv',
    'Dalian',
    'Zhenjiang',
    'Guangzhou',
    'Dharan',
    'Lalitpur',
    'Poltava',
    'Chittagong',
    'Sylhet',
    'Dhaka',
    'Rajshahi',
    'Shah Alam',
    'Olsztyn',
    'Pokhara',
    'Kirtipur',
    'Torun',
    'Kathmandu',
    'Bialystok',
    'Arkhangelsk',
    'Pskov',
    'Petaling Jaya',
    'Jenjarom',
    "St. George's",
    'Black River',
    'Whitehorse',
    'Tashkent',
    'Jamestown',
    'Winfield',
    'Athens',
    'Douai',
    'Breda',
    'Apeldoorn',
    'Lawrenceville',
    'Sandton',
    'Hamm',
    'Urgench',
    'County Clare',
    'Moncton',
    'Crewe',
    'Cairo',
    'Mansoura',
    'Alexandria',
    'Trier',
    'Iserlohn',
    'Hof',
    'Rosenheim',
    'Deggendorf',
    'Magdeburg',
    'Saarbrucken',
    'Hildesheim',
    'New Brunswick',
    'Lubeck',
    'Malmo',
    'Passau',
    'Wismar',
    'Wildau',
    'Wernigerode',
    'Nuremberg',
    'Amberg',
    'Pforzheim',
    'Idstein',
    'Kaiserslautern',
    'Nurtingen',
    'Frederiksberg',
    'Kassel',
    'Antwerp',
    'Vienna',
    'Weingarten',
    'Bochum',
    'Kongens Lyngby',
    'Kempten',
  ];

  const latitudeValue = lat;
  const longitudeValue = lon;
  const maxDistance = 30000 * 1000;
  const query = {
    latitude: latitudeValue,
    longitude: longitudeValue,
  };
  const nearbyPlaces = nearbyCities(query);

  const pointFrom = point([latitudeValue, longitudeValue]);
  const maxDistanceInMeters = maxDistance
    ? maxDistance / 1000
    : maxDistance;
  const nearbyPlacesToShow = [];

  for (let i = 0; i < nearbyPlaces.length; i++) {
    if (
      Math.ceil(
        distance(
          pointFrom,
          point([nearbyPlaces[i].lat, nearbyPlaces[i].lon]),
          {
            units: 'meters',
          },
        ),
      ) < maxDistanceInMeters &&
      citiesConstants.includes(
        nearbyPlaces[i].name
          .normalize('NFD')
          .replace(/[\u0300-\u036f]/g, ''),
      )
    ) {
    //   console.log(nearbyPlaces[i].name);
      nearbyPlacesToShow.push(nearbyPlaces[i].name);
    }
  }

  return nearbyPlacesToShow;
}
